# Data Ops Approval Matrix Configuration

# Environment-based Approval Requirements
environments:
  development:
    required_approvals: 1
    approvers:
      - role: "developer"
        required: true
      - role: "tech_lead"
        required: false
    auto_deploy: true
    rollback_approval_required: false
    
  staging:
    required_approvals: 2
    approvers:
      - role: "tech_lead"
        required: true
      - role: "data_ops_lead"
        required: true
      - role: "qa_lead"
        required: false
    auto_deploy: true
    rollback_approval_required: false
    validation_tests_required: true
    
  production:
    required_approvals: 3
    approvers:
      - role: "tech_lead"
        required: true
      - role: "data_ops_lead"
        required: true
      - role: "engineering_manager"
        required: true
      - role: "security_lead"
        required: false
    auto_deploy: false
    rollback_approval_required: true
    maintenance_window_required: true
    business_approval_required: true

# Risk Level-based Approval Requirements
risk_levels:
  LOW:
    description: "Minor schema changes, adding columns, indexes"
    required_approvals: 2
    approvers:
      - "tech_lead"
      - "data_ops_lead"
    can_auto_deploy: true
    staging_validation_required: true
    rollback_plan_required: true
    estimated_downtime: "< 5 minutes"
    
  MEDIUM:
    description: "Table modifications, data migrations, constraint changes"
    required_approvals: 3
    approvers:
      - "tech_lead"
      - "data_ops_lead"
      - "engineering_manager"
    can_auto_deploy: false
    staging_validation_required: true
    performance_testing_required: true
    rollback_plan_required: true
    backup_required: true
    estimated_downtime: "5-30 minutes"
    
  HIGH:
    description: "Major schema changes, dropping tables/columns, large data migrations"
    required_approvals: 4
    approvers:
      - "tech_lead"
      - "data_ops_lead"
      - "engineering_manager"
      - "cto"
    can_auto_deploy: false
    staging_validation_required: true
    performance_testing_required: true
    security_review_required: true
    business_approval_required: true
    rollback_plan_required: true
    backup_required: true
    maintenance_window_required: true
    estimated_downtime: "> 30 minutes"

# Team Roles and Responsibilities
team_roles:
  developer:
    permissions:
      - create_migration
      - test_locally
      - submit_for_review
    responsibilities:
      - "Write migration and rollback scripts"
      - "Perform local testing"
      - "Document migration impact"
      
  tech_lead:
    permissions:
      - approve_low_risk
      - approve_medium_risk
      - approve_high_risk
      - deploy_to_staging
    responsibilities:
      - "Review technical implementation"
      - "Validate rollback procedures"
      - "Approve deployment to staging"
      
  data_ops_lead:
    permissions:
      - approve_all_risks
      - deploy_to_production
      - emergency_rollback
      - override_approvals
    responsibilities:
      - "Review data impact and integrity"
      - "Validate backup procedures"
      - "Monitor migration execution"
      - "Coordinate maintenance windows"
      
  engineering_manager:
    permissions:
      - approve_medium_risk
      - approve_high_risk
      - schedule_maintenance
    responsibilities:
      - "Business impact assessment"
      - "Resource allocation"
      - "Stakeholder communication"
      
  security_lead:
    permissions:
      - security_review
      - approve_security_sensitive
    responsibilities:
      - "Security impact assessment"
      - "Compliance validation"
      - "Access control review"
      
  qa_lead:
    permissions:
      - validate_staging
      - approve_testing
    responsibilities:
      - "Test plan validation"
      - "Staging environment testing"
      - "Quality assurance sign-off"

# Approval Workflow States
workflow_states:
  draft:
    description: "Migration created but not submitted"
    allowed_actions:
      - edit
      - submit_for_review
      - delete
    next_states:
      - under_review
      
  under_review:
    description: "Migration submitted for technical review"
    allowed_actions:
      - approve
      - request_changes
      - reject
    next_states:
      - approved
      - changes_requested
      - rejected
      
  changes_requested:
    description: "Changes requested by reviewers"
    allowed_actions:
      - edit
      - resubmit
      - withdraw
    next_states:
      - under_review
      - withdrawn
      
  approved:
    description: "Migration approved for deployment"
    allowed_actions:
      - deploy_to_staging
      - schedule_production
    next_states:
      - staging_deployed
      - production_scheduled
      
  staging_deployed:
    description: "Migration deployed to staging"
    allowed_actions:
      - validate
      - promote_to_production
      - rollback
    next_states:
      - staging_validated
      - production_scheduled
      - rolled_back
      
  staging_validated:
    description: "Migration validated in staging"
    allowed_actions:
      - schedule_production
      - promote_to_production
    next_states:
      - production_scheduled
      - production_deployed
      
  production_scheduled:
    description: "Migration scheduled for production"
    allowed_actions:
      - deploy_to_production
      - reschedule
      - cancel
    next_states:
      - production_deployed
      - cancelled
      
  production_deployed:
    description: "Migration deployed to production"
    allowed_actions:
      - validate
      - monitor
      - emergency_rollback
    next_states:
      - completed
      - rolled_back
      
  completed:
    description: "Migration successfully completed"
    allowed_actions:
      - archive
    next_states:
      - archived
      
  rolled_back:
    description: "Migration rolled back"
    allowed_actions:
      - investigate
      - resubmit
    next_states:
      - under_investigation
      - draft
      
  rejected:
    description: "Migration rejected"
    allowed_actions:
      - resubmit
      - withdraw
    next_states:
      - draft
      - withdrawn

# Emergency Procedures
emergency_procedures:
  critical_failure:
    immediate_actions:
      - "Stop all migration processes"
      - "Assess data integrity"
      - "Notify incident response team"
      - "Initiate emergency rollback if safe"
    approval_override:
      roles:
        - "data_ops_lead"
        - "engineering_manager"
        - "cto"
      required_approvals: 2
      
  data_corruption:
    immediate_actions:
      - "Isolate affected systems"
      - "Restore from backup"
      - "Investigate root cause"
      - "Implement data recovery"
    approval_override:
      roles:
        - "data_ops_lead"
        - "cto"
      required_approvals: 2
      
  performance_degradation:
    immediate_actions:
      - "Monitor system metrics"
      - "Identify bottlenecks"
      - "Apply performance fixes"
      - "Consider rollback if severe"
    approval_override:
      roles:
        - "data_ops_lead"
        - "engineering_manager"
      required_approvals: 1

# Notification Settings
notifications:
  channels:
    slack:
      webhook_url_env: SLACK_WEBHOOK_URL
      channels:
        - "#data-ops"
        - "#engineering"
        - "#alerts"
    email:
      smtp_server: smtp.company.com
      recipients:
        - "dataops@company.com"
        - "engineering@company.com"
    pagerduty:
      service_key_env: PAGERDUTY_SERVICE_KEY
      
  triggers:
    migration_submitted:
      channels: ["slack"]
      recipients: ["data_ops_lead", "tech_lead"]
      
    migration_approved:
      channels: ["slack", "email"]
      recipients: ["submitter", "approvers"]
      
    migration_deployed:
      channels: ["slack", "email"]
      recipients: ["all_stakeholders"]
      
    migration_failed:
      channels: ["slack", "email", "pagerduty"]
      recipients: ["data_ops_team", "engineering_team"]
      urgency: "high"
      
    rollback_initiated:
      channels: ["slack", "email", "pagerduty"]
      recipients: ["all_stakeholders"]
      urgency: "critical"

# Audit and Compliance
audit:
  retention_period: "7 years"
  required_fields:
    - migration_id
    - submitter
    - approvers
    - approval_timestamps
    - deployment_timestamps
    - rollback_history
    - risk_assessment
    - business_justification
    
  compliance_checks:
    - gdpr_compliance
    - sox_compliance
    - hipaa_compliance
    - pci_compliance
    
  reporting:
    frequency: "monthly"
    recipients:
      - "compliance_team"
      - "audit_team"
      - "data_ops_lead"
    
# SLA and Performance Metrics
sla:
  approval_time:
    low_risk: "4 hours"
    medium_risk: "24 hours"
    high_risk: "72 hours"
    
  deployment_time:
    staging: "30 minutes"
    production: "2 hours"
    
  rollback_time:
    target: "15 minutes"
    maximum: "1 hour"
    
  success_rate:
    target: "99.5%"
    minimum: "95%"