groups:
  - name: system_health
    rules:
      # High CPU Usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 2m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 2 minutes on {{ $labels.instance }}"

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 2m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for more than 2 minutes on {{ $labels.instance }}"

      # Disk Space Low
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"}) * 100 < 10
        for: 1m
        labels:
          severity: critical
          team: infrastructure
        annotations:
          summary: "Disk space is running low"
          description: "Disk space is below 10% on {{ $labels.instance }} filesystem {{ $labels.mountpoint }}"

  - name: service_health
    rules:
      # Service Down
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          team: backend
        annotations:
          summary: "Service is down"
          description: "{{ $labels.job }} service is down for more than 1 minute"

      # High Error Rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 2m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for {{ $labels.job }} service"

      # High Response Time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 2m
        labels:
          severity: warning
          team: backend
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 1 second for {{ $labels.job }} service"

      # Database Connection Issues
      - alert: DatabaseConnectionHigh
        expr: pg_stat_activity_count > 80
        for: 2m
        labels:
          severity: warning
          team: database
        annotations:
          summary: "High database connections"
          description: "PostgreSQL has more than 80 active connections"

  - name: business_metrics
    rules:
      # Low Upload Success Rate
      - alert: LowUploadSuccessRate
        expr: rate(file_uploads_total{status="success"}[5m]) / rate(file_uploads_total[5m]) * 100 < 95
        for: 5m
        labels:
          severity: warning
          team: product
        annotations:
          summary: "Low file upload success rate"
          description: "File upload success rate is below 95% for the last 5 minutes"

      # High Authentication Failures
      - alert: HighAuthFailures
        expr: rate(auth_attempts_total{status="failed"}[5m]) > 10
        for: 2m
        labels:
          severity: warning
          team: security
        annotations:
          summary: "High authentication failure rate"
          description: "Authentication failure rate is above 10 per second"

      # Low User Activity
      - alert: LowUserActivity
        expr: rate(user_actions_total[1h]) < 100
        for: 10m
        labels:
          severity: info
          team: product
        annotations:
          summary: "Low user activity detected"
          description: "User activity is below 100 actions per hour"

  - name: container_health
    rules:
      # Container High CPU
      - alert: ContainerHighCPU
        expr: rate(container_cpu_usage_seconds_total[5m]) * 100 > 80
        for: 2m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "Container high CPU usage"
          description: "Container {{ $labels.name }} CPU usage is above 80%"

      # Container High Memory
      - alert: ContainerHighMemory
        expr: container_memory_usage_bytes / container_spec_memory_limit_bytes * 100 > 85
        for: 2m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "Container high memory usage"
          description: "Container {{ $labels.name }} memory usage is above 85%"

      # Container Restart
      - alert: ContainerRestart
        expr: increase(container_start_time_seconds[1h]) > 0
        for: 0m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "Container restarted"
          description: "Container {{ $labels.name }} has restarted"

  - name: network_health
    rules:
      # High Network Traffic
      - alert: HighNetworkTraffic
        expr: rate(node_network_receive_bytes_total[5m]) + rate(node_network_transmit_bytes_total[5m]) > 100000000
        for: 5m
        labels:
          severity: info
          team: infrastructure
        annotations:
          summary: "High network traffic"
          description: "Network traffic is above 100MB/s on {{ $labels.instance }}"

      # Network Errors
      - alert: NetworkErrors
        expr: rate(node_network_receive_errs_total[5m]) + rate(node_network_transmit_errs_total[5m]) > 0
        for: 2m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "Network errors detected"
          description: "Network errors detected on {{ $labels.instance }} interface {{ $labels.device }}"