global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'microservice-local'
    environment: 'development'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
    metrics_path: /metrics

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s
    metrics_path: /metrics

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # File Service
  - job_name: 'file-service'
    static_configs:
      - targets: ['file-service:8082']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # User Service
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8083']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # Analytics Service
  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8085']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  # API Gateway (Nginx)
  - job_name: 'nginx'
    static_configs:
      - targets: ['api-gateway:80']
    metrics_path: /metrics
    scrape_interval: 15s

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://auth-service:8081/health
        - http://file-service:8082/health
        - http://user-service:8083/health
        - http://analytics-service:8085/health
        - http://api-gateway:80/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Remote write configuration for production
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"